### Get all products
GET http://localhost:5000/api/v1/products

### Fetch product by ID
GET http://localhost:5000/api/v1/products/60d24b29c8e0734264bed8ce


### Create product
POST http://localhost:5000/api/v1/products
Content-Type: application/json

{
    "name": "circle",
    "description": "it's round",
    "price": 50
}

### Update product
PUT http://localhost:5000/api/v1/products/60d24b29c8e0734264bed8ce
Content-Type: application/json

{
    "name": "circle",
    "description": "it's round",
    "variation": "green",
    "price": 50
}

### Add review
PUT http://localhost:5000/api/v1/products/review/60d24b29c8e0734264bed8ce
Content-Type: application/json

{
    "userID": "0917823071301987",
    "username": "John Doe",
    "message": "Wow! It's round!"
}

### Delete product
DELETE http://localhost:5000/api/v1/products/60d00dd25f5fb60850cebc51